agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('submit/', views.TalkSubmitView.as_view(), name='talks-submit'),
    path('edit/<int:pk>/', views.TalkEditView.as_view(), name='talks-edit'),
    path('', views.TalkListView.as_view(), name='talks-list'),
    path('<int:pk>/', views.TalkDetailView.as_view(), name='talks-detail'),
]

conference_auth/urls.py
from django.urls import path
from . import views
# import logout view
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='users-register'),
    path('login', views.LoginUserView.as_view(), name='users-login'),
    path('logout', LogoutView.as_view(), name='users-logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('conference_auth.urls')),
    path('', include('agenda.urls')),
    path('admin/', admin.site.urls),
]

agenda/models.py
from django.db import models
from django.core.validators import RegexValidator
from conference_auth.models import ConferenceUser
from django.urls import reverse_lazy

# Create your models here.
# Creating a site for a conference
# Potential speakers will submit talks for approval
# Talks will be approved or rejected by staff

# Create status choices
STATUS_CHOICES = (
    ('submitted', 'Submitted'),
    ('approved', 'Approved'),
    ('rejected', 'Rejected'),
)

class Track(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.name

class Talk(models.Model):
    title = models.CharField(max_length=255, unique=True)
    abstract = models.TextField()
    status = models.CharField(max_length=255, choices=STATUS_CHOICES, default='submitted')
    track = models.ForeignKey(Track, on_delete=models.PROTECT)
    speaker = models.ForeignKey(ConferenceUser, on_delete=models.PROTECT)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('talks-detail', args=[str(self.id)])

conference_auth/models.py
# Creating custom user model for Django
# The custom user needs to have fields for address, zip code, city and state
# The custom user also needs to have a field for the user's phone number

from django.db import models
from django.contrib.auth.models import AbstractUser

class ConferenceUser(AbstractUser):
    # Override first_name and last_name to make required
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    bio = models.TextField(blank=True)
    linkedin = models.URLField(blank=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

conference_auth/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Div
from django import forms
from .models import ConferenceUser

# Import login form
from django.contrib.auth.forms import AuthenticationForm

class ConferenceUserForm(forms.ModelForm):
    class Meta:
        model = ConferenceUser
        fields = [
            'username',
            'password',
            'first_name',
            'last_name',
            'email',
            'bio',
            'linkedin',
        ]
        # set password as password widget
        widgets = {
            'password': forms.PasswordInput(),
        }
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.label_class = 'col-sm-4'
        self.helper.field_class = 'col-sm-8'
        self.helper.layout.append(Submit('submit', 'Register!'))

class LoginForm(AuthenticationForm):
    class Meta:
        model = ConferenceUser
        fields = [
            'username',
            'password',
        ]
        # set password as password widget
        widgets = {
            'password': forms.PasswordInput(),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # set up crispy form helper
        self.helper = FormHelper(self)
        self.helper.form_method = 'POST'
        self.helper.label_class = 'col-sm-4'
        self.helper.field_class = 'col-sm-8'
        self.helper.layout.append(Submit('submit', 'Login!'))

agenda/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView
from .models import Talk
from django.contrib.auth.mixins import LoginRequiredMixin

# Create submit talk view
class TalkSubmitView(LoginRequiredMixin, CreateView):
    model = Talk
    fields = ['title', 'abstract', 'track']
    template_name = 'edit.html'
    success_url = '/'

    # Add title and button text to context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Submit talk for consideration'
        context['button_text'] = 'Submit talk'
        return context

    def form_valid(self, form):
        form.instance.speaker = self.request.user
        return super().form_valid(form)

# Create update talk view
class TalkEditView(LoginRequiredMixin, UpdateView):
    model = Talk
    fields = ['title', 'abstract', 'track']
    template_name = 'edit.html'
    success_url = '/'

    # Add title and button text to context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Update talk'
        context['button_text'] = 'Update'
        return context

    def form_valid(self, form):
        return super().form_valid(form)

# Create list view to display talks
# Accept status as a filter
class TalkListView(ListView):
    model = Talk
    template_name = 'list.html'
    context_object_name = 'talks'

# Create detail view
class TalkDetailView(DetailView):
    model = Talk
    template_name = 'detail.html'
    context_object_name = 'talk'

conference_auth/views.py
from typing import Any
from django.shortcuts import render

from .models import ConferenceUser
# import generic views
from django.views.generic import CreateView

# import login view
from django.contrib.auth.views import LoginView

from .forms import ConferenceUserForm, LoginForm
from django.contrib.auth import authenticate, login

# import messages
from django.contrib import messages

# Create your views here.

# Create registration view
class RegisterView(CreateView):
    model = ConferenceUser
    form_class = ConferenceUserForm
    template_name = 'generic_form.html'
    success_url = '/'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Register'
        context['header'] = 'Sign up for an account'
        context['button_text'] = 'Register'
        return context

    def form_valid(self, form):
        # Save the user first, then add the user to the group
        # create the user
        user = form.save()
        # set the password
        user.set_password(form.cleaned_data.get('password'))
        # save the user
        user.save()
        return super().form_valid(form)

# Create login view
class LoginUserView(LoginView):
    template_name = 'generic_form.html'
    success_url = '/'
    form_class = LoginForm

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Login'
        context['header'] = 'Login to your account'
        context['button_text'] = 'Login'
        return context
    
    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')

        user = authenticate(self.request, username=username, password=password)

        if user is not None:
            login(self.request, user)
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self) -> str:
        # Get next from querystring
        # If no value, return to /
        next_url = self.request.GET.get('next', '/')
        return next_url

agenda/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>

    <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css" />
</head>
<body>
    <div class="container">

        <section class="jumbotron">
            <h1 class="display-4">GitHub Demo Conference</h1>
            <p class="lead">Learn about the latest GitHub features and technologies from experts at our virtual event</p>
            <hr class="my-4" />
            <div class="row">
                {% if user.is_authenticated %}
                    <div class="col-md-6">
                        <h4>Welcome back, {{ user }}!</h4>
                    </div>
                    <div class="col-md-3 text-right">
                        <a href="{% url 'agenda:talks-submit' %}" class="btn btn-info">Submit talk</a>
                    </div>
                    <div class="col-md-3">
                        <form action="{% url 'users-logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-info">Logout</button>
                        </form>
                    </div>
                {% else %}
                    <div class="col-md-1">
                        <a href="{% url 'users-login' %}" class="btn btn-info">Login</a>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'users-register' %}" class="btn btn-info">Register</a>
                    </div>
                {% endif %}
            </div>
        </section>


        
        {% block content %}{% endblock content %}

        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </div>
</body>
</html>

agenda/templates/detail.html
{% extends 'base.html' %}

{% block title %}
{{ talk.title }}
{% endblock %}


{% block content %}
    <h3>{{ talk.title }}</h3>
    <p>{{ talk.title }}</p>
    <p>{{ talk.abstract }}</p>
    <p>Presented by {{ talk.speaker }}</p>

    {% if user.is_authenticated %}
        <p><a href="{% url 'agenda:talks-edit' talk.id %}" class="btn btn-info">Edit</a></p>
    {% endif %}
    <p><a href="{% url 'agenda:talks-list' %}">Back to all talks</a></p>
{% endblock %}

agenda/templates/edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
    <h2>{{ title }}</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">{{ button_text }}</button>
    </form>
{% endblock %}

agenda/templates/list.html
{% extends 'base.html' %}

{% block title %}Submitted sessions{% endblock %}

{% block content %}
    <h3>Submitted sessions</h3>

    <!-- django loop through all talks using list-group and list-group-item -->
    <div class="list-group">
        {% for talk in talks %}
        <a href="{% url 'agenda:talks-detail' talk.id %}" class="list-group-item list-group-item-action">
            <section class="row">
                <div class="col-7">{{ talk.title }}</div>
                <div class="col-5 text-right">{{ talk.speaker }}</div>
            </section>
        </a>
        {% endfor %}
    </div>
{% endblock %}

conference_auth/templates/generic_form.html
{% load crispy_forms_tags %}

<html>
    <head>
        <title>{{ title }}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">    </head>

    <body>
        <!-- display username if logged in -->
        {{ user.username }}

        <div class="container">
            <h1>{{ header }}</h1>
            <form method="POST">
                {% csrf_token %}
                {% crispy form %}
            </form>
        </div>
    </body>
</html>